### ISSUE TITLE
Avaliação final de Front-end

### ISSUE THREAD

**Issue by gabjohann** [gabjohann/RSTI#6]
Nossa UC se aproxima do fim e como forma de consolidar os conhecimentos adquiridos ao longo do curso, em específico desta unidade curricular. Vocês deverão desenvolver um site para uma pizzaria seguindo os seguintes critérios:

  - Mobile first;
  - Responsividade;
  - HTML semântico;
  - Pixel perfect;
  - Código devidamente identado;
  - Tipografia e paleta de cores declaradas em variáveis, com nome condizente;
  - Commits descritivos;
  - Aplicação hospedada na vercel ou github pages (indiferente);
  - Deverá ser desenvolvida em aula e de forma individual.

Segue o link do layout: [Figma](https://www.figma.com/design/i36fuIV0ZD8Arsfxxo0k9k/exerc%C3%ADcio-final?node-id=0-1&t=n5qXTwMt3DE1iyBm-1)
Segue o link para entrega da avalição: [Forms](https://forms.gle/Ntd5QY61SGGTV4Y67)

**Comment by dieizo** [comment]
[RESUMO-HTML.pdf](https://github.com/user-attachments/files/17592882/RESUMO-HTML.pdf)
